@startuml
actor ユーザー
actor 管理者
left to right direction
rectangle ショッピングサイト{
	ユーザー --> (ログイン)
	ユーザー --> (商品検索)
	ユーザー --> (閲覧)
	ユーザー --> (購入)
	ユーザー --> (購入履歴を見る)
	ユーザー --> (問い合わせ)

	(ログイン) <-- 管理者
	(閲覧) <-- 管理者
	(商品管理) <-- 管理者
	(売れ行きを確認) <-- 管理者
}
@enduml